### ISSUE TITLE
set false doesn't work

### ISSUE THREAD

**Issue by arteck** [walli545/ioBroker.time-switch#26] opened 2020-04-21 04:37 UTC
![grafik](https://user-images.githubusercontent.com/6681528/79825827-691e0a00-839a-11ea-97da-fbae980b951a.png)

here a little program

```
on({id: '0_userdata.0.wohnung.test', change: 'any'}, function() {
    let wahr = getState('0_userdata.0.wohnung.test').val;
    if (wahr) {
        log.console('jo läuft für true');           
    } else {
          log.console('jo läuft für false');   
    }
});

```

**Comment by walli545** [comment] 2020-04-21 09:52
Thanks, but this is a duplicate of #19, so I will close this issue

**Closed** 2020-04-21 09:55 UTC
