### ISSUE TITLE
Set the Level for Dimmer

### ISSUE THREAD

**Issue by FuXXz** [walli545/ioBroker.time-switch#121] opened 2020-12-02 13:04 UTC
Hi,

if you use 0 for off and 100 for on, for dimmer, then you cant controll the level. You can only switch on / off to the values you set up in the vis.

is it possible to enter a numerical value instead of on / off?

**Comment by walli545** [comment] 2020-12-02 14:59
Hi,
this is not possible at the moment. You are only able to set the on value to for example 50 to always switch the lamp on to 50 percent.
This is a duplicate of #16 so i will close this issue. At the moment i don't think i will have time to implement this in the near future.

**Closed by walli545** 2020-12-02 14:59 UTC
